strict_mode = false
sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
dir_length = 3


[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "aws-governance "
path = "~/projects/aws-governance"
startup_command = "dev_setup"

[[session]]
name = "Dotfiles ⚙️"
path = "~/projects/dotfiles"
startup_command = "dev_setup"


[[session]]
name = "findings automation "
path = "~/projects/findings-automation"
startup_command = "dev_setup"

