strict_mode = false
sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
dir_length = 3


[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Ubuntu 24_04 Dotfiles ⚙️"
path = "~/projects/ubuntu2404_dotfiles"
startup_command = "tmux-dev-setup"

